### ISSUE TITLE
How to translate to another language?

### ISSUE THREAD

**Issue by PeterDaveHello** [JunichiIto/be_vimmer#2]
Hi there, is there any instruction for translating be_vimmer to another language? Thanks!

**Comment by JunichiIto** [comment]
If you want to translate to other languages, the following steps will be required:

1. Insert manual data into be_vimmer database with custom script, like this => https://github.com/JunichiIto/be_vimmer/blob/master/lib/tasks/insert_en.rake
1. Create a new Twitter account.
1. Setup a new scheduler setting on Heroku.

For step 1, I extract description from Vim manual, like this => https://code.google.com/p/vim/source/browse/runtime/doc/index.txt

Once I wrote a blog post in Japanese when I released be_vimmer. It might help you to understand how it works (Please translate it by yourself, though): http://blog.jnito.com/entry/20120415/1334452212

**Comment by PeterDaveHello** [comment]
Thanks!
